name: "Code Quality check : Front"

on:
  pull_request:
    paths:
      - ".github/workflows/front-code-quality.yml"
      - "front/**"
jobs:
  Conformity-Check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Checking Code Conformity with Style Guidelines"
        run: |
          cd front
          yarn
          yarn lint:check
        env:
          CI: true

  Unit-Tests-Check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Running Unit Tests with Coverage Report"
        run: |
          cd front
          yarn
          yarn test:cov
        env:
          CI: true
